(package "gptscript-mode"
         "0.0.1"
         "Major mode for editing GPTScript natural language")

(website-url "https://github.com/emacs-openai/gptscript-mode")
(keywords "languages")

(package-file "gptscript-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
